name: Vulnerability & CodeQL Check with SARIF/JSON

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  vuln-codeql-json:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and run Grype scan
        run: |
          GRYPE_VERSION=$(curl -s https://api.github.com/repos/anchore/grype/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "Using Grype version: $GRYPE_VERSION"
          curl -sSfL "https://github.com/anchore/grype/releases/download/${GRYPE_VERSION}/grype_${GRYPE_VERSION#v}_linux_amd64.tar.gz" -o grype.tar.gz
          tar -xzf grype.tar.gz
          chmod +x grype
          ./grype . -o json > grype-output.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install npm dependencies for script
        run: npm install
        working-directory: ./scripts
      - name: Generate CodeQL query
        run: node scripts/generate_codeql_from_grype.js
      - name: Show CodeQL query
        run: cat queries/CheckVulnerablePkgs.ql

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL analysis (SARIF)
        uses: github/codeql-action/analyze@v3
        with:
          query-suite: queries/custom-queries.qls

      - name: Download CodeQL CLI
        run: |
          LATEST_CODEQL_VERSION=$(curl -s https://api.github.com/repos/github/codeql-cli-binaries/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "Latest CodeQL version: $LATEST_CODEQL_VERSION"
          wget https://github.com/github/codeql-cli-binaries/releases/download/${LATEST_CODEQL_VERSION}/codeql-linux64.zip
          unzip codeql-linux64.zip
          echo "$PWD/codeql" >> $GITHUB_PATH

      - name: Run CodeQL query for SARIF output (CLI)
        run: |
          mkdir -p results
          ./codeql/codeql query run queries/custom-queries.qls \
            --database=codeql_databases/javascript \
            --format=sarif \
            --output=results/codeql-results.sarif

      - name: Copy SARIF to JSON extension for downstream tools
        run: cp results/codeql-results.sarif results/codeql-results.json

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif-results
          path: results/codeql-results.sarif

      - name: Upload "JSON" (SARIF-JSON) artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-json-results
          path: results/codeql-results.json

