name: Vulnerability & CodeQL Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  vulnerability-codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Run Grype on repo and save as JSON
      - name: Download and run Grype (JSON)
        run: |
          curl -sSfL https://github.com/anchore/grype/releases/latest/download/grype-linux-amd64 > grype
          chmod +x grype
          ./grype . -o json > grype-output.json

      # Step 2: Generate CodeQL query from Grype JSON
      - name: Set up Node.js for query generation
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install
        working-directory: ./scripts
      - name: Generate CodeQL query
        run: node scripts/generate_codeql_from_grype.js

      # Step 3: Set up CodeQL and run custom query
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          query: ./queries/CheckVulnerablePkgs.ql

      # Optional: List SARIF files
      - name: List SARIF files
        run: find . -name '*.sarif'

      # Step 4: Upload SARIF results
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: ./codeql-results/codeql.sarif
