name: Vulnerability & CodeQL Only Output

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  codeql-only-json:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node setup and CodeQL query steps as before
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies for scripts
        run: npm install
        working-directory: ./scripts
      - name: Generate CodeQL query from Grype
        run: node scripts/generate_codeql_from_grype.js

      - name: List CodeQL queries
        run: ls -l queries/ && head -20 queries/*.ql
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: ./queries/CheckVulnerablePkgs.ql
      
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
      
      - name: Check SARIF file size and contents
        run: |
          SARIF_FILE=$(find . -type f -name '*.sarif' | grep results/ | head -1)
          echo "SARIF file path: $SARIF_FILE"
          if [ -s "$SARIF_FILE" ]; then
            echo "SARIF file is not empty. Here are the first 100 lines:"
            head -100 "$SARIF_FILE"
          else
            echo "SARIF file is empty."
            exit 1
          fi
      
      - name: Rename SARIF to JSON
        run: |
          SARIF_FILE=$(find . -type f -name '*.sarif' | grep results/ | head -1)
          mv "$SARIF_FILE" codeql-output.json
      
      - name: Upload CodeQL JSON result
        uses: actions/upload-artifact@v4
        with:
          name: codeql-json-output
          path: codeql-output.json

