name: Vulnerability & CodeQL Check with JSON Output

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  vuln-codeql-json:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Download and run Grype to generate JSON output
      - name: Download and run Grype scan
        run: |
          GRYPE_VERSION=$(curl -s https://api.github.com/repos/anchore/grype/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "Using Grype version: $GRYPE_VERSION"
          curl -sSfL "https://github.com/anchore/grype/releases/download/${GRYPE_VERSION}/grype_${GRYPE_VERSION#v}_linux_amd64.tar.gz" -o grype.tar.gz
          tar -xzf grype.tar.gz
          chmod +x grype
          ./grype . -o json > grype-output.json

      # Step 2: Setup Node.js and install script dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install npm dependencies for script
        run: npm install
        working-directory: ./scripts

      # Step 3: Generate CodeQL query from Grype scan
      - name: Generate CodeQL query
        run: node scripts/generate_codeql_from_grype.js

      # Debug: Show generated query contents
      - name: Show CodeQL query
        run: cat queries/CheckVulnerablePkgs.ql

      # Step 4: Initialize CodeQL env (auto CLI download and DB creation)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      # Step 5: Analyze using GitHub CodeQL Action (produces SARIF)
      - name: Perform CodeQL analysis (SARIF)
        uses: github/codeql-action/analyze@v3
        with:
          query-suite: queries/custom-queries.qls

      # Debug: list SARIF files & show snippet
      - name: List SARIF files and head results
        run: |
          find . -name '*.sarif'
          head -40 results/javascript.sarif || true

      # Step 6: Run CodeQL CLI directly to generate JSON output
      - name: Run CodeQL query for JSON output
        run: |
          mkdir -p results
          codeql query run queries/custom-queries.qls \
            --database=codeql_databases/javascript \
            --format=json \
            --output=results/codeql-results.json

      # Step 7: Upload SARIF results artifact
      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif-results
          path: results/*.sarif

      # Step 8: Upload JSON results artifact
      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-json-results
          path: results/codeql-results.json
