name: Vulnerability & CodeQL Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  vuln-codeql:
    runs-on: ubuntu-latest

    steps:
      # Step 0: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Download and run Grype scan (output JSON)
      - name: Download and run Grype scan
        run: |
          GRYPE_VERSION=$(curl -s https://api.github.com/repos/anchore/grype/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "Using Grype version: $GRYPE_VERSION"
          curl -sSfL "https://github.com/anchore/grype/releases/download/${GRYPE_VERSION}/grype_${GRYPE_VERSION#v}_linux_amd64.tar.gz" -o grype.tar.gz
          tar -xzf grype.tar.gz
          chmod +x grype
          ./grype . -o json > grype-output.json

      # Step 2: Set up Node.js for script execution
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install Node.js dependencies for scripts
      - name: Install dependencies for scripts
        run: npm install
        working-directory: ./scripts

      # Step 4: Generate CodeQL query from Grype
      - name: Generate CodeQL query from Grype
        run: node scripts/generate_codeql_from_grype.js

      # Step 5: List queries for confirmation (optional)
      - name: List CodeQL queries
        run: ls -l queries/ && head -40 queries/*.ql

      # Step 6: Initialize CodeQL (custom query path)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: ./queries/CheckVulnerablePkgs.ql

      # Step 7: Perform CodeQL analysis
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

      # Step 8: Rename SARIF files to .json for easy downstream JSON consumption (optional)
      - name: Rename SARIF files to JSON
        run: |
          find . -name '*.sarif' -exec bash -c 'mv "$0" "${0%.sarif}.json"' {} \;

      # Step 9: Upload CodeQL JSON results
      - name: Upload CodeQL JSON results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-json-results
          path: '**/*.json'

      # Step 10: Upload Grype JSON results
      - name: Upload Grype JSON results
        uses: actions/upload-artifact@v4
        with:
          name: grype-json-results
          path: grype-output.json
