name: Vulnerability & CodeQL Query Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  vuln-codeql-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Grype Scan
      - name: Download and run Grype scan
        run: |
          GRYPE_VERSION=$(curl -s https://api.github.com/repos/anchore/grype/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "Using Grype version: $GRYPE_VERSION"
          curl -sSfL "https://github.com/anchore/grype/releases/download/${GRYPE_VERSION}/grype_${GRYPE_VERSION#v}_linux_amd64.tar.gz" -o grype.tar.gz
          tar -xzf grype.tar.gz
          chmod +x grype
          ./grype . -o json > grype-output.json

      # Node.js for automation scripts
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install script dependencies
        run: npm install
        working-directory: ./scripts

      # Download CodeQL CLI
      - name: Download CodeQL CLI
        run: |
          wget https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip
          unzip codeql-linux64.zip

      # Install CodeQL query pack dependencies
      - name: Install CodeQL Pack Dependencies
        run: |
          ./codeql/codeql pack install queries

      # Create CodeQL database
      - name: Create CodeQL database
        run: |
          ./codeql/codeql database create db --language=javascript --source-root=.

      # Run CodeQL Query 
      - name: Run CodeQL Query
        run: |
          ./codeql/codeql query run queries/C1.ql --database=db --output=result.bqrs

      # Convert BQRS to JSON
      - name: Convert BQRS to JSON
        run: |
          mkdir -p codeql-json-output
          ./codeql/codeql bqrs decode result.bqrs --format=json > codeql-json-output/codeql-output.json

      # Upload only the CodeQL output as JSON
      - name: Upload CodeQL JSON results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-output-json
          path: codeql-json-output/codeql-output.json
